apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    pod-template-hash: 76df748b9
    run: nginx
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    pod-template-hash: 76df748b9
    run: nginx
  type: NodePort
status:
  loadBalancer: {}
